### ISSUE TITLE
Need finer grained permissions for page manager pages

### ISSUE THREAD

**Issue by jrreid** [ucalgary/ucalgary_layout#1]
See https://www.drupal.org/sandbox/chrishks/2094111

**Comment by dmcb** [comment]
Very useful. Though I think I may have spotted some bugs. Added in 1faa98a03d1fcb965c30eec06836eea67abb2f32.

**Comment by dmcb** [comment]
Negative on the bugs. This is working nicely. I moved the permissions to ucalgary_layout in b51d366ab6e9c742862dcaa583bada988ec039d3.
